version: '3'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel/otel-collector-config.yaml
    ports:
      - "4317:4317"
    depends_on:
      - zipkin

  service_a:
    container_name: service_a
    build:
      context: ./service_a
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
      - otel-collector
      - service_b

  service_b:
    container_name: service_b
    build:
      context: ./service_b
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - otel-collector